# controllers:
#     web_controller:
#         resource: ../../src/Controller/Delault/
#         type: annotation
#     rest_controller:
#         resource: ../../src/Controller/Rest/
#         type: annotation
#         prefix: /api