version: "3.5"
services:
  php:
    build: ./php/
    volumes:
      - ../:/var/www//sources
    links:
      - db
  server:
    build: ./server/
    restart: always
    volumes:
      - ../:/var/www/sources
      - ./server/conf.d/:/etc/nginx/conf.d
    ports:
      - "8484:80"
    links:
      - php
  db:
    build: ./db/
    ports:
        - "5432:5432"
    restart: always    
    volumes :
        - "./db/data:/var/lib/postgresql/data"
    environment
        -  "POSTGRES_HOST=db"
        -  POSTGRES_USER=postgres
        -  POSTGRES_PASSWORD=postgrespwd
        -  POSTGRES_DB=astro_db
